global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'monitoring@vandelay-labs.com'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
    # Email configuration (uncomment and configure when ready)
    # email_configs:
    #   - to: 'admin@vandelay-labs.com'
    #     subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       {{ end }}

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
    # Slack configuration (uncomment and configure when ready)
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#monitoring'
    #     title: 'Warning: {{ .GroupLabels.alertname }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
