global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for Docker VM monitoring
  - job_name: 'node-exporter-docker'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter for native macOS monitoring
  # Run with: node_exporter --web.listen-address=":9101"
  - job_name: 'node-exporter-macos'
    static_configs:
      - targets: ['host.docker.internal:9101']
    scrape_interval: 5s
    metrics_path: /metrics

  # Windows Exporter for Windows machine monitoring
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['192.168.68.55:9182']
    scrape_interval: 5s
    metrics_path: /metrics

  # File-based service discovery for additional hosts
  - job_name: 'hosts'
    file_sd_configs:
      - files:
        - 'targets/hosts.yml'
        refresh_interval: 5m

  # Placeholder for future database monitoring
  - job_name: 'databases'
    file_sd_configs:
      - files:
        - 'targets/databases.yml'
        refresh_interval: 5m

  # PostgreSQL database monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 5s
    metrics_path: /metrics

  # Redis cache monitoring
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 5s
    metrics_path: /metrics

  # RabbitMQ message queue monitoring
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 5s
    metrics_path: /metrics

  # MongoDB database monitoring
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 5s
    metrics_path: /metrics

  # Placeholder for future Kubernetes monitoring
  - job_name: 'kubernetes'
    file_sd_configs:
      - files:
        - 'targets/kubernetes.yml'
        refresh_interval: 5m
